name: Lint Code Base

on: [push]

jobs:
  super-lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_PYTHON: true
          VALIDATE_SHELL_SHFMT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
